<script>
export default {
  name: 'NotificationConditionsEN',
  props: {
    localeIn: { type: String, default: undefined }
  },
  data() {
    return {
      locale
    }
  },
  beforeMount() {
    this.locale = this.localeIn || 'es';
  }
}
</script>

<template>
  <div class="text">
    <p>It's Your Turn ("we", "our" or "us") is committed to protecting your privacy. This Privacy Policy explains how It's Your Turn collects, uses and discloses your personal information.
    </p>
    <p>This Privacy Policy applies to our websites, estuturno.app, estuturno.net and its associated subdomains (collectively, our "Service") together with our application, It's Your Turn. By accessing or using our Service, you indicate that you have read, understood and agree to our collection, storage, use and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.</p>
    <h5>Definitions and Key Terms</h5>
    <p>To help explain things as clearly as possible in this Privacy Policy, whenever any of these terms are referred to, they are strictly defined as:
    <ul>
    <li>Cookie – A small amount of data generated by a website and stored by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
    <li>Company: When this policy mentions "Company", "we", "us" or "our", it refers to It's Your Turn (Guardia Vieja 202, Providencia), which is responsible for your information under this Policy privacy.</li>
    <li>Platform: It's Your Turn Internet website, web application or public-facing digital application.</li>
    <li>Country: where It's Your Turn is located or the owners / founders of It's Your Turn, in this case it is VE</li>
    <li>Customer: refers to the company, organization or person that registers to use the It's Your Turn Service to manage relationships with its consumers or users of the service.</li>
    <li>Device: any device connected to the Internet, such as a phone, tablet, computer or any other device that can be used to visit It's Your Turn and use the services.</li>
    <li>IP Address: Every device connected to the Internet is assigned a number known as an Internet Protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device connects to the Internet.</li>
    <li>Personal: refers to those people who are employed by It's Your Turn or are under contract to perform a service on behalf of one of the parties.</li>
    <li>Personal data: any information that directly, indirectly or in connection with other information, including a personal identification number, allows the identification of a natural person.</li>
    <li>Service: refers to the service provided by It's Your Turn as described in the relative terms (if available) and on this platform.</li>
    <li>Third Parties: refers to advertisers, contest sponsors, marketing and promotional partners, and others who provide our content or whose products or services we believe may interest you.</li>
    <li>Website: the It's Your Turn site, which can be accessed through these URLs: estuturno.app, estuturno.net</li>
    <li>You: a person or entity that is registered with It's Your Turn to use the Services.</li>
    </ul>
    </p>
    <h5>What information do we collect?</h5>
    <p>We collect information from you when you visit our platform, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</p>
    <ul><li>Name/username</li><li>Phone numbers</li><li>Emails</li><li>Email addresses</li><li>Billing addresses </li><li>Age</li><li>Password</li>
    </ul>
    <p>We also collect information from mobile devices for a better user experience, although these features are completely optional:</p><ul><li>Location (GPS): Location data helps create an accurate representation of your interests, and this can be used to bring more targeted and relevant ads to potential customers. </li><li>Camera (images): Giving permission to the camera allows the user to upload any image directly from the platform, you can deny securely set camera permissions for this platform.</li>
    </ul>
    <h5>How do we use the information we collect?</h5>
    <p>Any of the information we collect from you may be used in one of the following ways:
    <ul>
    <li>To personalize your experience (your information helps us better respond to your individual needs)</li>
    <li>To improve our platform (we continually strive to improve what our platform offers based on the information and feedback we receive from you)</li>
    <li>To improve customer service (your information helps us respond to more effectively address your customer service requests and support needs)</li>
    <li>To process transactions</li>
    <li>To administer a contest, promotion, survey, or other site feature</li>
    <li>To send periodic emails</li>
    </ul>
    </p>
    <h5>When does It's Your Turn use third-party end-user information?</h5>
    <p>It's Your Turn will collect the end user data necessary to provide the It's Your Turn services to our customers.</p>
    <p>End users may voluntarily provide us with information that they have made available on social media websites. If you provide us with such information, we may collect publicly available information from the social media websites you have indicated. You can control the amount of information that social media websites make public by visiting these websites and changing your privacy settings.</p>
    <h5>When does It's Your Turn use third-party customer information?</h5>
    <p>We receive information from third parties when you communicate with us. For example, when you submit your email address to us to indicate interest in becoming an It's Your Turn customer, we receive information from a third party that provides automated fraud detection services to It's Your Turn. From time to time, we also collect information that is made publicly available on social media websites. You can control the amount of information that social media websites make public by visiting these websites and changing your privacy settings.</p>
    <h5>Do we share the information we collect with third parties? </h5>
    <p>We may share the information we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, marketing and promotional partners, and others who provide our content or whose products or services we believe may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, sale of assets or other business reorganization, we may also share or transfer your personal and non-personal information to our successors in interest.</p >
    <p>We may engage trusted third-party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and platform, database storage and management, email management, storage marketing , credit card processing, servicing and fulfilling orders for products and services that you may purchase through the platform. We may share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and you.</p>
    <p>We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, app developers, and advertising networks. If your IP address is shared, it may be used to estimate general location and other technological data, such as connection speed, whether you have visited the Platform in a shared location, and the type of device used to visit the Platform. They can aggregate information about our advertising and what you see on the platform and then provide audits, research and reports for us and our advertisers.</p>
    <p>We may also disclose personal and non-personal information about you to government, law enforcement officials or private third parties as we believe, in our sole discretion, necessary or appropriate to respond to claims, legal process (including subpoenas) , to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical or legally actionable activity, or to comply with court orders, applicable laws, rules and regulations . </p>
    <h5>Where and when is information collected from customers and end users? </h5>
    <p>It's Your Turn will collect the personal information you send us. We may also receive personal information about you from third parties as described above.</p>
    <h5>How do we use your email address?</h5>
    <p>By submitting your email address on this platform, you agree to receive emails from us. You may opt out of any of these email lists at any time by clicking on the opt-out link or other unsubscribe option included in the respective email. We only send emails o to people who have authorized us to contact them, either directly or through a third party. We don't send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display personalized advertising to specific people who have opted in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates related to your order. However, if you have provided us with the same email through another method, we may use it for any of the purposes set out in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.</p>
    <h5>How long do we keep your information?</h5>
    <p>We retain your information only as long as we need it to provide It's Your Turn to you and fulfill the purposes described in this policy. This is also the case for anyone with whom we share your information and who performs services on our behalf. When we no longer need to use your information and it is no longer necessary for us to retain it to comply with our legal or regulatory obligations, we will delete it from our systems or depersonalize it so that we cannot identify you.</p>
    <h5>How do we protect your information?</h5>
    <p>We implement a variety of security measures to maintain the security of your personal information when you place an order, enter, submit or access your personal information. We offer the use of a secure server. All confidential/credit information supplied is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and must keep information confidential. After a transaction, your private information (credit cards, social security numbers, finances, etc.) is never archived. However, we cannot guarantee the absolute security of any information you transmit to It's Your Turn or guarantee that your information on the Service will not be accessed, disclosed, altered or destroyed by a breach of any of our physical, technical or management safeguards. .</p>
    <h5>Could my information be transferred to other countries?</h5>
    <p>It's Your Turn is incorporated into VE. Information collected through our website, through direct interactions with you, or through the use of our support services may be transferred from time to time to our offices or staff, or to third parties, located around the world, and may be viewed and be hosted anywhere in the world, including countries that may not have generally applicable laws regulating the use and transfer of such data. To the fullest extent permitted by applicable law, by using any of the above, you voluntarily consent to the cross-border transfer and hosting of such information.
    </p>
    <h5>Is the information collected through the It's Your Turn Service secure?</h5>
    <p>We take precautions to protect the security of your information. We have physical, electronic and administrative procedures in place to help safeguard, prevent unauthorized access, maintain data security and correctly use your information. However, neither people nor security systems are infallible, including encryption systems. Additionally, people may commit intentional crimes, make mistakes, or fail to follow policies. Therefore, although we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any unwaivable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.</p>
    <h5>Can I update or correct my information?</h5>
    <p>The rights you have to request updates or corrections to the information It's Your Turn collects depend on your relationship with It's Your Turn. Staff may update or correct their information as detailed in our internal company employment policies.</p>
    <p>Customers have the right to request restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us to (1) update or correct your personally identifiable information, (2) change your preferences regarding communications and other information you receive from us, or (3) delete personally identifiable information maintained about you in our system (subject to the following paragraph) , canceling your account. Such updates, corrections, changes and deletions will have no effect on other information we maintain or information we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To protect your privacy and security, we may take reasonable steps (such as requiring a unique password) to verify your identity before granting you access to your profile or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times.</p>
    <p>You should be aware that it is not technologically possible to delete each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a form that cannot be erased and will be difficult or impossible for us to locate. Immediately upon receipt of your request, all personal information stored in the databases we actively use and other easily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically feasible. possible.</p>
    <p>If you are an end user and would like to update, delete or receive any information we have about you, you can do so by contacting the organization of which you are a customer.</p>
    <h5>Personnel</h5>
    <p>If you are an It's Your Turn worker or applicant, we collect the information you voluntarily provide to us. We use the information collected for human resources purposes to administer employee benefits and select applicants.</p>
    <p>You may contact us to (1) update or correct your information, (2) change your preferences regarding communications and other information you receive from us, or (3) receive a record of the information we have related to you. you. Such updates, corrections, changes and deletions will have no effect on other information we maintain or information we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.</p>
    <h5>Business Sale</h5>
    <p>We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of It's Your Turn or any of its corporate affiliates (as defined herein), or the portion of It's Your Turn or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed a petition against us in the event of bankruptcy, reorganization or similar proceeding , provided that the third party agrees to adhere to the terms of this Privacy Policy.</p>
    <h5>Affiliates</h5>
    <p>We may disclose information (including personal information) about you to our corporate affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity that directly or indirectly controls, is controlled by, or is under common control with It's Your Turn, whether by ownership or otherwise. Any information relating to you that we provide to our corporate affiliates will be treated by such corporate affiliates in accordance with the terms of this privacy policy.</p>
    <h5>Governing Law</h5>
    <p>This Privacy Policy is governed by the laws of VE without regard to its conflict of law provisions. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy, except for those persons who may have the right to bring claims under the Privacy Shield or the Swiss-American mark.</p>
    <p>The laws of VE, excluding its conflicts of laws, will govern this Agreement and your use of the Platform. Your use of the Platform may also be subject to other local, state, national or international laws.</p>
    <p>By using It's Your Turn or contacting us directly, you agree to this Privacy Policy. If you do not agree to this Privacy Policy, you should not interact with our website or use our services. Continued use of the site website, direct interaction with us or following the posting of changes to this Privacy Policy that do not materially affect the use or disclosure of your personal information will mean that you accept those changes.</p>
    <h5>Your consent</h5>
    <p>We have updated our Privacy Policy to give you full transparency about what is set when you visit our site and how it is used. By using our platform, registering an account or making a purchase, you hereby accept our Privacy Policy and agree to its terms.</p>
    <h5>Links to other Websites</h5>
    <p>This Privacy Policy applies only to the Services. The Services may contain links to other websites that It's Your Turn does not operate or control. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those linked to on our platform, is subject to that website's own rules and policies. These third parties may use their own cookies or other methods to collect information about you.</p>
    <h5>Advertising</h5>
    <p>This platform may contain third-party advertisements and links to third-party sites. It's Your Turn makes no representation as to the accuracy or suitability of the information contained in those advertisements or sites and accepts no responsibility or liability for the conduct or content of those advertisements and sites and the offers made by third parties.</p>
    <p>Advertising keeps It's Your Turn and many of the websites and services you use free of charge. We work hard to make sure ads are safe, discreet and as relevant as possible.</p>
    <p>Third-party advertisements and links to other sites where goods or services are advertised are not endorsements or recommendations by It's Your Turn of the third-party sites, goods or services. It's Your Turn assumes no responsibility for the content of the advertisements, the promises made or the quality/reliability of the products or services offered in all advertisements.</p>
    <h5>Cookies for Advertising</h5>
    <p>These cookies collect information over time about your online activity on the platform and other online services to make online advertising more relevant and effective for you. This is known as interest-based advertising. They also perform functions such as preventing the same ad from continually reappearing and ensuring that ads are displayed correctly to advertisers. Without cookies, it is very difficult for an advertiser to reach their audience or know how many ads were shown and how many clicks they received.</p>
    <h5>Cookies</h5>
    <p>It's Your Turn uses "cookies" to identify the areas of our website that you have visited. A cookie is a small piece of data that your web browser stores on your computer or mobile device. We use cookies to improve the performance and functionality of our platform, but they are not essential for its use. However, without these cookies, certain features, such as videos, may not be available or you may be asked to enter your login details each time you visit the platform as we would not be able to remember that you had logged in previously. Most web browsers can be configured to disable the use of cookies. However, if you disable cookies, you may not be able to access the functionality of our website correctly or at all. We never place personally identifiable information in cookies.</p>
    <h5>Block and disable Cookies and similar technologies</h5>
    <p>Wherever you are, you can also set your browser to block cookies and similar technologies, but this may block our essential cookies and prevent our website from functioning properly, and you may not be able to use all of its features and services. completely. You should also be aware that you may also lose saved information (e.g. saved login details, site preferences) if you block cookies in your browser. Different browsers provide different controls. Disabling a cookie or a cookie category does not delete the cookie from your browser, you will need to do this yourself from your browser, you should visit your browser's help menu for more information.</p>
    <h5>Remarketing Services</h5>
    <p>We use remarketing services. What is remarketing? In digital marketing, remarketing (or retargeting) is the practice of serving ads on the Internet to people who have already visited your website. It allows your business to appear to be "following" people across the internet by serving ads on the websites and platforms they use most.</p>
    <h5>Children's Privacy</h5>
    <p>We collect information from children under 13 years of age only to improve our services. If you are a parent or guardian and you are aware that your child has provided us with personal data without their permission, please contact us. If we become aware that we have collected personal data from anyone under the age of 13 without verification of parental consent, we take steps to delete that information from our servers.</p>
    <h5>Changes to our Privacy Policy</h5>
    <p>We may change our Service and our policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and our policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you the opportunity to review them before they become effective. Then, if you continue to use the Service, you will be subject to the updated Privacy Policy. If you do not wish to accept this or any updated Privacy Policy, you may delete your account.</p>
    <h5>Third party services</h5>
    <p>We may display, include or make available third party content (including data, information, applications and other product services) or provide links to third party websites or services ("Third Party Services").</p>
    <p>You acknowledge and agree that It's Your Turn will not be responsible or liable for any Third Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. It's Your Turn does not and will not have any obligation or liability to you or any other person or entity for any Third Party Services.</p>
    <p>Third Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third party's terms and conditions.</p>
    <h5>Tracking Technologies</h5>
    <ul><li>Google Maps API
    <br><br>
    <p>The Google Maps API is a robust tool that can be used to create a custom map, search map, check-in functions, show live data sync with location, plan routes or create a mashup, just to name a few.</p>
    <p>The Google Maps API may collect information from you and your device for security purposes.</p>
    <p>The Google Maps API collects information that is maintained in accordance with its Privacy Policy.</p></li><br><li>Cookies
    <br><br>
    <p>We use Cookies to improve the performance and functionality of our platform, but they are not essential for its use. However, without these cookies, certain features, such as videos, may not be available or you may be asked to enter your login details each time you visit the platform as we would not be able to remember that you had logged in previously. </p>
    </li><br><li>Sessions
    <br><br>
    <p>$thename uses "Sessions" to identify the areas of our website that you have visited. A session is a small piece of data that your web browser stores on your computer or mobile device.</p></li><br>
    </ul>
    <h5>Information about the General Data Protection Regulation (GDPR)</h5>
    <p>We may collect and use information about you if you are located in the European Economic Area (EEA), and in this section of our Privacy Policy we will explain exactly how and why this data is collected, and how we keep it protected from replication or incorrect use.</p>
    <h5>What is GDPR?</h5>
    <p>GDPR is an EU-wide data protection and privacy law that regulates how companies protect the data of EU residents and improves the control that EU residents have over their personal data.</p >
    <p>The GDPR is relevant to any company operating globally and not just to companies based in the EU and EU residents. Our customers' data is important regardless of where it is located, which is why we have implemented GDPR controls as our gold standard for all our operations around the world.</p>
    <h5>What is Personal Data?</h5>
    <p>Any data that relates to an identifiable or identifiable individual. The GDPR covers a broad spectrum of information that could be used alone or in combination with other pieces of information to identity a person. Personal data goes beyond a person's name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP addresses, physical address, sexual orientation and ethnicity.</p>
    <p>Data protection principles include requirements such as:</p>
    <ul>
    <li>Personal data collected must be processed fairly, lawfully and transparently and must only be used in the way that a person would reasonably expect.</li>
    <li>Personal data should only be collected to fulfill a specific purpose and should only be used for that purpose. Organizations must specify why they need the personal data when they collect it.</li>
    <li>Personal data should not be kept longer than necessary to fulfill its purpose.</li>
    <li>Individuals covered by the GDPR have the right to access their own personal data. They can also request a copy of their data and that their data be updated, deleted, restricted or moved to another organization.</li>
    </ul>
    <h5>Why is the GDPR important?</h5>
    <p>GDPR adds some new requirements regarding how companies must protect the personal data of individuals they collect and process. It also raises the stakes for compliance by increasing enforcement and imposing higher fines for noncompliance. Beyond these facts, it is simply the right thing to do. At It's Your Turn we firmly believe that the privacy of your data is very important and we already have solid security and privacy practices that go beyond the requirements of this new regulation.</p>
    <h5>Individual rights of the interested party: access, portability and deletion of data</h5>
    <p>We are committed to helping our clients comply with the data subject rights requirements of the GDPR. It's Your Turn processes or stores all personal data with DPA compliant and fully vetted providers. We store all conversations and personal data for up to 6 years, unless your account is deleted. In which case, we delete all data in accordance with our Terms of Service and Privacy Policy, but we will not retain it for longer than 60 days.</p>
    <p>We are aware that if you work with EU clients, you must be able to provide them with the ability to access, update, retrieve and delete personal data. We have been set up as self-service from the beginning and have always given you access to your data and your customers' data. Our customer support team is here to answer any questions you may have about working with the API.</p>
    <h5>California Residents</h5>
    <p>The California Consumer Privacy Act (CCPA) requires us to disclose the categories of Personal Information we collect and how we use it, the categories of sources from which we collect Personal Information, and the third parties with whom we share it, which we have explained previously. </p>
    <p>We are also required to communicate information about the rights that California residents have under California law. You can exercise the following rights:</p>
    <ul>
    <li>Right to know and access. You may submit a verifiable request for information regarding: (1) categories of Personal Information that we collect, use or share; (2) purposes for which we collect or use categories of personal information; (3) categories of sources from which we collect personal information; and (4) specific pieces of personal information we have collected about you.</li>
    <li>Right to equal service. We will not discriminate against you if you exercise your privacy rights.</li>
    <li>Right to delete. You may submit a verifiable request to close your account and we will delete the Personal Information about you that we have collected.</li>
    <li>Request that a company that sells a consumer's personal data not sell the consumer's personal data.</li>
    </ul>
    <p>If you make a request, we have one month to respond. If you wish to exercise any of these rights, please contact us.</p>
    <p>We do not sell our users' personal information.</p>
    <p>For more information about these rights, please contact us.</p>
    <h5>California Online Privacy Protection Act (CalOPPA)</h5>
    <p>CalOPPA requires that we disclose the categories of personal information we collect and how we use it, the categories of sources from which we collect personal information, and the third parties with whom we share it, which we explain above.</p>
    <p>CalOPPA users have the following rights:</p>
    <ul>
    <li>Right to know and access. You can submit a request verifiable information regarding: (1) categories of Personal Information that we collect, use or share; (2) purposes for which we collect or use categories of personal information; (3) categories of sources from which we collect personal information; and (4) specific pieces of personal information we have collected about you.</li>
    <li>Right to equal service. We will not discriminate against you if you exercise your privacy rights.</li>
    <li>Right to delete. You may submit a verifiable request to close your account and we will delete the Personal Information about you that we have collected.</li>
    <li>Right to request that a company that sells a consumer's personal data not sell the consumer's personal data.</li>
    </ul>
    <p>If you make a request, we have one month to respond. If you wish to exercise any of these rights, please contact us.</p>
    <p>We do not sell our users' personal information.</p>
    <p>For more information about these rights, please contact us.</p>
    <h5>Contact us</h5>
    <p>Please feel free to contact us if you have any questions.</p>
    <ul><li>Through email: hola@estuturno.app</li><li>Through this link: https://estuturno.app</li></ul>
  </div>
</template>

<style scoped>
.details {
  line-height: normal;
}
.text {
  overflow-y: scroll;
  height:400px;
  font-size: small;
  margin-bottom: 2rem;
  padding: 1rem;
  border-radius: .5rem;
  border: .5px solid var(--gris-default);
  text-align: justify;
  text-justify: inter-word;
}
</style>